# Runs all tests and pushes coverage report to codeclimate
name: Coverage

on:  # Runs on all push events to master branch and any push related to a pull request
  push:
    branches:
      - master
  pull_request:  # so that codeclimate gets coverage and reports on the diff

jobs:
  coverage:
      uses: pylhc/.github/.github/workflows/coverage.yml@master
      with:
        src-dir: tfs      
        pytest-options: --ignore=tests/test_hdf.py  # skip HDF tests for now as pytables is not ok with numpy 2.0
      secrets: inherit
