# Runs all tests on master on Mondays at 3 am (UTC time)
name: Cron Testing


on: 
  schedule:
    - cron:  '* 3 * * mon'

jobs:
    tests:
      uses: pylhc/.github/.github/workflows/cron.yml@master
      with:
        extra-dependencies: test,hdf5
        pytest-options: --ignore=tests/test_hdf.py  # TODO: restore HDF tests when pytables is ok with numpy 2.0
