# Runs all tests 
name: All Tests

defaults:
  run:
    shell: bash

on:  # Runs on any push event to any branch except master (the coverage workflow takes care of that)
  push:
    branches-ignore:
      - 'master'

env:
  UV_SYSTEM_PYTHON: 1  # lets uv pip install in the python installed by uv (no need for venv step)

jobs:
  tests:
    uses: pylhc/.github/.github/workflows/tests.yml@uv
    with:
      extra-dependencies: test  # test includes hdf5 dependency specifier
